[tool.poetry]
name = "intellinoun"
version = "0.0.1"
description = "Various scripts and datasets for Nouns LLM."
authors = ["lituus"]
license = "UNLICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.2"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
